version: "3.9"

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ENV=production
    volumes:
      - ./logs:/app/logs
      - ./config/config.yaml:/config/config.yaml
    restart: unless-stopped